In [3]:
import numpy as np
list1 = [1,2,3,4]
array1 = np.array(list1)
array1

array([1, 2, 3, 4])

In [4]:
list2 = [11,22,33,44]
semualist = [list1,list2]
array2 = np.array(list2)
array2

array([11, 22, 33, 44])

In [5]:
list2 = [11,22,33,44]
semualist = [list1,list2]
array2 = np.array(semualist)
array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [6]:
array2.shape

(2, 4)

In [7]:
array2.dtype

dtype('int64')

In [8]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [9]:
zero_array = np.zeros(5)
zero_array.dtype

dtype('float64')

In [10]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [11]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [12]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])