In [1]:
import numpy as np
array = np.arange(11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
np.sqrt(array)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [3]:
np.exp(array)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [4]:
A = np.random.randn(10)
A

array([-0.11852366, -0.75573326,  1.35732842, -2.20129015,  0.80868091,
       -0.41635646, -1.36589153, -1.57990359,  1.35067198,  0.2754136 ])

In [5]:
B = np.random.randn(10)
B

array([-0.82091165,  1.18619373,  1.14349896,  1.5527998 ,  0.91530616,
        0.52177864, -1.25568052,  0.30253233,  0.00886802, -0.62816038])

In [6]:
#bianry function
np.add(A,B)

array([-0.93943531,  0.43046047,  2.50082737, -0.64849035,  1.72398706,
        0.10542218, -2.62157205, -1.27737126,  1.35954   , -0.35274678])

In [7]:
np.maximum(A,B)

array([-0.11852366,  1.18619373,  1.35732842,  1.5527998 ,  0.91530616,
        0.52177864, -1.25568052,  0.30253233,  1.35067198,  0.2754136 ])