In [1]:
import numpy as np
array = np.arange(11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
np.sqrt(array)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(array)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
A = np.random.randn(10)
A

array([ 0.87091495,  1.09958703,  1.25879718, -0.77389463,  1.63834333,
       -1.35691914,  0.07203766,  0.90506949, -0.26144454,  0.06973533])

In [6]:
B = np.random.randn(10)
B

array([-0.70518778, -0.05560255, -0.18693244,  0.29108997,  0.28112783,
        0.22273447, -0.76721438,  0.83354688, -1.29326992, -0.28022869])

In [7]:
#binary functions
np.add(A,B)

array([ 0.16572716,  1.04398448,  1.07186474, -0.48280466,  1.91947116,
       -1.13418467, -0.69517672,  1.73861637, -1.55471445, -0.21049336])

In [8]:
np.maximum(A,B)

array([ 0.87091495,  1.09958703,  1.25879718,  0.29108997,  1.63834333,
        0.22273447,  0.07203766,  0.90506949, -0.26144454,  0.06973533])

In [9]:
website = "http://mutiarauliya.com"
import webbrowser
webbrowser.open(website)

True